version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: fastapi_db
    ports:
      - 5432:5432
    volumes:
      - ./dump-sample.sql:/docker-entrypoint-initdb.d/dump-sample.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=q7963q
      - POSTGRES_DB=fastapiDB
    networks:
      - lab-network
  prometheus:
    image: prom/prometheus
    container_name: fastapi_prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - lab-network
  fastapi:
    build: ./fastapi_crud
    container_name: fastapi_crud
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes: 
      - ./fastapi_crud:/app
    networks:
      - lab-network
  frontend:
    build: ./frontend-react-produtos
    container_name: frontend-react-produtos
    ports:
      - "3000:80" # Porta externa 3000, interna 80 do nginx
    depends_on:
      - fastapi
    restart: always
    #volumes: 
    #  - ./frontend-react-produtos:/src
    networks:
      - lab-network

volumes:
  postgres_data:

networks: 
  lab-network:
    driver: bridge


# docker-compose up -d
# docker start 
#
# App:
# http://127.0.0.1:5000/
# http://127.0.0.1:5000/docs
#
#
# Prometheus:
# http://127.0.0.1:9090/
